### ISSUE TITLE
Quotefault doesn't prevent two of the same quote

### ISSUE THREAD

**Issue by jabbate19** [ComputerScienceHouse/quotefault-backend#3]
<img width="452" alt="image" src="https://github.com/costowell/quotefault-backend/assets/40615740/436f67d5-e6a5-4cff-a758-14cb3b71b2fc">

**Comment by costowell** [comment]
What cases are we trying to prevent? I can only really think of one in which two people quote the *exact* same thing twice. In my opinion, the better approach is to stick to allowing quoters to delete and let people curate and regulate quotefault themselves. Worst case is an RTP or eboard member hides it.
